module.exports = {
	// Keys and other mathematical constants
	KEY_BREAK: 112,
	KEY_ENTER: 13,
//	KEY_LEFT: 37,
//	KEY_UP: 38,
//	KEY_RIGHT: 39,
//	KEY_DOWN: 40,
//	KEY_DART: 101,
 	KEY_BOMB: 32,
	KEY_LEFT: 65,
 	KEY_UP: 87,
 	KEY_RIGHT: 68,
 	KEY_DOWN: 83,
	mobile: false,
	// Canvas
	screenWidth: window.innerWidth,
	screenHeight: window.innerHeight,
	gameWidth: 0,
	gameHeight: 0,
	xoffset: -0,
	yoffset: -0,
	gameStart: false,
	disconnected: false,
	died: false,
	kicked: false,
	backgroundColor: '#000495',
	lineColor: '#ffffff',
	pieceColor: ["#ee0000", "#f0c000", "#5555ff"]
};
